general.import = [ "~/.config/themes/current/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono", style = "Regular" }
bold = { family = "JetBrainsMono", style = "Bold" }
italic = { family = "JetBrainsMono", style = "Italic" }
bold_italic = { family = "JetBrainsMono", style = "Bold Italic" }
size = 14.0

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 1

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

